-- Highlights for the plugins actually installed in this config.
local c = require 'zedokai.palette'

return {
  --------------------------------------------------------------- neo-tree --
  NeoTreeNormal = { fg = c.fg, bg = c.bg },
  NeoTreeNormalNC = { fg = c.fg, bg = c.bg },
  NeoTreeEndOfBuffer = { fg = c.bg, bg = c.bg },
  NeoTreeWinSeparator = { fg = c.border, bg = c.bg },
  NeoTreeCursorLine = { bg = c.bg_element },
  NeoTreeRootName = { fg = c.fg, bold = true },
  NeoTreeDirectoryName = { fg = c.fg },
  NeoTreeDirectoryIcon = { fg = c.fg_muted },
  NeoTreeFileName = { fg = c.fg },
  NeoTreeFileIcon = { fg = c.fg_muted },
  NeoTreeFileNameOpened = { fg = c.fg },
  NeoTreeSymbolicLinkTarget = { fg = c.type },
  NeoTreeIndentMarker = { fg = c.bg_element }, -- deliberately dim
  NeoTreeExpander = { fg = c.fg_muted },
  NeoTreeDotfile = { fg = c.hidden },
  NeoTreeHiddenByName = { fg = c.hidden },
  NeoTreeDimText = { fg = c.line_nr },
  NeoTreeMessage = { fg = c.fg_muted, italic = true },
  NeoTreeModified = { fg = c.modified },
  NeoTreeFilterTerm = { fg = c.accent, bold = true },
  NeoTreeTitleBar = { fg = c.fg, bg = c.bg_element },
  NeoTreeFloatBorder = { fg = c.border_float, bg = c.bg_panel },
  NeoTreeFloatTitle = { fg = c.fg, bg = c.bg_panel, bold = true },
  NeoTreeTabActive = { fg = c.fg, bg = c.bg, bold = true },
  NeoTreeTabInactive = { fg = c.fg_muted, bg = c.bg_panel },
  NeoTreeTabSeparatorActive = { fg = c.bg, bg = c.bg },
  NeoTreeTabSeparatorInactive = { fg = c.bg_panel, bg = c.bg_panel },
  NeoTreeGitAdded = { fg = c.created },
  NeoTreeGitModified = { fg = c.modified },
  NeoTreeGitDeleted = { fg = c.deleted },
  NeoTreeGitRenamed = { fg = c.modified },
  NeoTreeGitStaged = { fg = c.created },
  NeoTreeGitUnstaged = { fg = c.modified },
  NeoTreeGitUntracked = { fg = c.created },
  NeoTreeGitConflict = { fg = c.conflict },
  NeoTreeGitIgnored = { fg = c.ignored },

  --------------------------------------------------------------------- fff --
  FFFNormal = { fg = c.fg, bg = c.bg },
  FFFBorder = { fg = c.border_float, bg = c.bg },
  FFFTitle = { fg = c.fg, bg = c.bg, bold = true },
  FFFCursor = { fg = c.fg, bg = c.bg_cursorline },

  -------------------------------------------------------------- telescope --
  TelescopeNormal = { fg = c.fg, bg = c.bg_panel },
  TelescopeBorder = { fg = c.border_float, bg = c.bg_panel },
  TelescopeTitle = { fg = c.fg, bold = true },
  TelescopePromptNormal = { fg = c.fg, bg = c.bg_element },
  TelescopePromptBorder = { fg = c.bg_element, bg = c.bg_element },
  TelescopePromptTitle = { fg = c.bg, bg = c.accent, bold = true },
  TelescopePromptPrefix = { fg = c.accent, bg = c.bg_element },
  TelescopePromptCounter = { fg = c.fg_muted, bg = c.bg_element },
  TelescopeResultsNormal = { fg = c.fg_dim, bg = c.bg_panel },
  TelescopeResultsBorder = { fg = c.bg_panel, bg = c.bg_panel },
  TelescopeResultsTitle = { fg = c.bg_panel, bg = c.bg_panel },
  TelescopePreviewNormal = { fg = c.fg, bg = c.bg },
  TelescopePreviewBorder = { fg = c.border_float, bg = c.bg },
  TelescopePreviewTitle = { fg = c.bg, bg = c.func, bold = true },
  TelescopeSelection = { fg = c.fg, bg = c.bg_element },
  TelescopeSelectionCaret = { fg = c.accent, bg = c.bg_element },
  TelescopeMultiSelection = { fg = c.constant, bg = c.bg_element },
  TelescopeMultiIcon = { fg = c.constant },
  TelescopeMatching = { fg = c.accent, bold = true },
  TelescopeResultsClass = { fg = c.type },
  TelescopeResultsField = { fg = c.property },
  TelescopeResultsFunction = { fg = c.func },
  TelescopeResultsIdentifier = { fg = c.variable },
  TelescopeResultsMethod = { fg = c.func },
  TelescopeResultsNumber = { fg = c.constant },
  TelescopeResultsComment = { fg = c.comment },
  -- Columns shared by the custom pickers -- references, live grep, harpoon and
  -- buffers (lua/core/picker_columns.lua and the entry makers beside it). The
  -- filename carries the colour, the directory recedes into comment grey behind
  -- it, and the position gets its own hue so numbers don't read as part of the
  -- path. Foreground only -- a background would tint the cell differently to the
  -- rest of the row.
  TelescopePickerFile = { fg = c.type },
  TelescopePickerDirectory = { fg = c.comment },
  TelescopePickerPosition = { fg = c.constant },
  TelescopePickerText = { fg = c.fg },

  TelescopeResultsDiffAdd = { fg = c.git_add },
  TelescopeResultsDiffChange = { fg = c.git_change },
  TelescopeResultsDiffDelete = { fg = c.git_delete },
  TelescopeResultsDiffUntracked = { fg = c.created },

  --------------------------------------------------------------- gitsigns --
  GitSignsAdd = { fg = c.git_add, bg = c.bg },
  GitSignsChange = { fg = c.git_change, bg = c.bg },
  GitSignsDelete = { fg = c.git_delete, bg = c.bg },
  GitSignsTopdelete = { fg = c.git_delete, bg = c.bg },
  GitSignsChangedelete = { fg = c.git_change, bg = c.bg },
  GitSignsUntracked = { fg = c.git_add, bg = c.bg },
  GitSignsAddNr = { fg = c.git_add },
  GitSignsChangeNr = { fg = c.git_change },
  GitSignsDeleteNr = { fg = c.git_delete },
  GitSignsAddLn = { bg = c.git_add_bg },
  GitSignsChangeLn = { bg = c.git_change_bg },
  GitSignsDeleteLn = { bg = c.git_delete_bg },
  GitSignsAddInline = { bg = c.git_word_add },
  GitSignsChangeInline = { bg = c.git_word_change },
  GitSignsDeleteInline = { bg = c.git_word_delete },
  GitSignsAddPreview = { bg = c.git_add_bg },
  GitSignsDeletePreview = { bg = c.git_delete_bg },
  GitSignsCurrentLineBlame = { fg = c.line_nr, italic = true },

  -------------------------------------------------------------- blink.cmp --
  BlinkCmpMenu = { fg = c.fg, bg = c.bg_panel },
  BlinkCmpMenuBorder = { fg = c.border_float, bg = c.bg_panel },
  BlinkCmpMenuSelection = { bg = c.bg_element, bold = true },
  BlinkCmpScrollBarThumb = { bg = c.bg_scrollbar },
  BlinkCmpScrollBarGutter = { bg = c.bg_panel },
  BlinkCmpLabel = { fg = c.fg, bg = c.bg_panel },
  BlinkCmpLabelDeprecated = { fg = c.fg_muted, strikethrough = true },
  BlinkCmpLabelMatch = { fg = c.accent, bold = true },
  BlinkCmpLabelDetail = { fg = c.fg_muted },
  BlinkCmpLabelDescription = { fg = c.fg_muted },
  BlinkCmpSource = { fg = c.line_nr },
  BlinkCmpGhostText = { fg = c.line_nr, italic = true },
  BlinkCmpDoc = { fg = c.fg, bg = c.bg_panel },
  BlinkCmpDocBorder = { fg = c.border_float, bg = c.bg_panel },
  BlinkCmpDocSeparator = { fg = c.border_float, bg = c.bg_panel },
  BlinkCmpDocCursorLine = { bg = c.bg_element },
  BlinkCmpSignatureHelp = { fg = c.fg, bg = c.bg_panel },
  BlinkCmpSignatureHelpBorder = { fg = c.border_float, bg = c.bg_panel },
  BlinkCmpSignatureHelpActiveParameter = { fg = c.accent, bold = true },
  BlinkCmpKind = { fg = c.fg_muted },
  BlinkCmpKindText = { fg = c.fg },
  BlinkCmpKindMethod = { fg = c.func },
  BlinkCmpKindFunction = { fg = c.func },
  BlinkCmpKindConstructor = { fg = c.type },
  BlinkCmpKindField = { fg = c.property },
  BlinkCmpKindVariable = { fg = c.variable },
  BlinkCmpKindClass = { fg = c.type },
  BlinkCmpKindInterface = { fg = c.type },
  BlinkCmpKindModule = { fg = c.keyword },
  BlinkCmpKindProperty = { fg = c.property },
  BlinkCmpKindUnit = { fg = c.constant },
  BlinkCmpKindValue = { fg = c.constant },
  BlinkCmpKindEnum = { fg = c.type },
  BlinkCmpKindKeyword = { fg = c.keyword },
  BlinkCmpKindSnippet = { fg = c.string_special },
  BlinkCmpKindColor = { fg = c.constant },
  BlinkCmpKindFile = { fg = c.fg_dim },
  BlinkCmpKindReference = { fg = c.string_special },
  BlinkCmpKindFolder = { fg = c.fg_dim },
  BlinkCmpKindEnumMember = { fg = c.constant },
  BlinkCmpKindConstant = { fg = c.constant },
  BlinkCmpKindStruct = { fg = c.type },
  BlinkCmpKindEvent = { fg = c.type },
  BlinkCmpKindOperator = { fg = c.operator },
  BlinkCmpKindTypeParameter = { fg = c.type },

  ----------------------------------------------------------------- neogit --
  NeogitBranch = { fg = c.type, bold = true },
  NeogitRemote = { fg = c.constant, bold = true },
  NeogitObjectId = { fg = c.fg_muted },
  NeogitSectionHeader = { fg = c.title, bold = true },
  NeogitFilePath = { fg = c.type, italic = true },
  NeogitCursorLine = { bg = c.bg_cursorline },
  NeogitFold = { fg = c.fg_muted },
  NeogitHunkHeader = { fg = c.fg_dim, bg = c.bg_element },
  NeogitHunkHeaderHighlight = { fg = c.fg, bg = c.bg_element, bold = true },
  NeogitDiffContext = { bg = c.bg },
  NeogitDiffContextHighlight = { bg = c.bg_cursorline },
  NeogitDiffAdd = { fg = c.git_add, bg = c.git_add_bg },
  NeogitDiffAddHighlight = { fg = c.created, bg = c.git_word_add },
  NeogitDiffDelete = { fg = c.git_delete, bg = c.git_delete_bg },
  NeogitDiffDeleteHighlight = { fg = c.deleted, bg = c.git_word_delete },
  NeogitDiffHeader = { fg = c.fg, bg = c.bg_element, bold = true },
  NeogitDiffHeaderHighlight = { fg = c.accent, bg = c.bg_element, bold = true },
  NeogitChangeAdded = { fg = c.created, bold = true },
  NeogitChangeModified = { fg = c.modified, bold = true },
  NeogitChangeDeleted = { fg = c.deleted, bold = true },
  NeogitChangeRenamed = { fg = c.modified, bold = true },
  NeogitChangeUpdated = { fg = c.warning, bold = true },
  NeogitChangeCopied = { fg = c.type, bold = true },
  NeogitChangeBothModified = { fg = c.conflict, bold = true },
  NeogitChangeNewFile = { fg = c.created, bold = true },
  NeogitUntrackedfiles = { fg = c.title, bold = true },
  NeogitUnstagedchanges = { fg = c.title, bold = true },
  NeogitStagedchanges = { fg = c.title, bold = true },
  NeogitStashes = { fg = c.title, bold = true },
  NeogitUnmergedInto = { fg = c.title, bold = true },
  NeogitUnpushedTo = { fg = c.title, bold = true },
  NeogitUnpulledFrom = { fg = c.title, bold = true },
  NeogitRecentcommits = { fg = c.title, bold = true },
  NeogitPopupSectionTitle = { fg = c.title, bold = true },
  NeogitPopupBranchName = { fg = c.type, bold = true },
  NeogitPopupActionKey = { fg = c.keyword, bold = true },
  NeogitPopupOptionKey = { fg = c.keyword, bold = true },
  NeogitPopupConfigKey = { fg = c.keyword, bold = true },
  NeogitPopupSwitchKey = { fg = c.keyword, bold = true },
  NeogitFloatHeader = { fg = c.fg, bg = c.bg_element, bold = true },
  NeogitFloatHeaderHighlight = { fg = c.accent, bg = c.bg_element, bold = true },

  --------------------------------------------------------------- codediff --
  -- Only groups codediff defines with `default = true` -- the line and word
  -- backgrounds are rebuilt from its `highlights` opts (plugins/codediff.lua).
  CodeDiffExplorerSelected = { bg = c.bg_element },
  CodeDiffExplorerTreeGroup = { fg = c.title, bold = true },
  ExplorerDirectorySmall = { fg = c.line_nr },
  CodeDiffStatusAdded = { fg = c.created },
  CodeDiffStatusModified = { fg = c.modified },
  CodeDiffStatusDeleted = { fg = c.deleted },
  CodeDiffStatusRenamed = { fg = c.modified },
  CodeDiffStatusUntracked = { fg = c.created },
  CodeDiffStatusConflict = { fg = c.conflict },

  ----------------------------------------------------------------- fidget --
  FidgetTitle = { fg = c.title, bold = true },
  FidgetTask = { fg = c.fg_muted },

  ------------------------------------------------------------------ mason --
  MasonNormal = { fg = c.fg, bg = c.bg_panel },
  MasonHeader = { fg = c.bg, bg = c.accent, bold = true },
  MasonHeaderSecondary = { fg = c.bg, bg = c.type, bold = true },
  MasonHighlight = { fg = c.type },
  MasonHighlightBlock = { fg = c.bg, bg = c.type },
  MasonHighlightBlockBold = { fg = c.bg, bg = c.type, bold = true },
  MasonMuted = { fg = c.fg_muted },
  MasonMutedBlock = { fg = c.fg_dim, bg = c.bg_element },
  MasonError = { fg = c.error },
  MasonWarning = { fg = c.warning },
  MasonHeading = { fg = c.fg, bold = true },
  MasonLink = { fg = c.link_uri, underline = true },

  ------------------------------------------------------------------- lazy --
  LazyNormal = { fg = c.fg, bg = c.bg_panel },
  LazyH1 = { fg = c.bg, bg = c.accent, bold = true },
  LazyH2 = { fg = c.fg, bold = true },
  LazyButton = { fg = c.fg_dim, bg = c.bg_element },
  LazyButtonActive = { fg = c.bg, bg = c.accent, bold = true },
  LazyProp = { fg = c.fg_muted },
  LazyReasonPlugin = { fg = c.keyword },
  LazyReasonEvent = { fg = c.warning },
  LazyReasonKeys = { fg = c.constant },
  LazyReasonStart = { fg = c.func },
  LazyReasonSource = { fg = c.string },
  LazyReasonFt = { fg = c.type },
  LazyReasonCmd = { fg = c.func },
  LazyReasonImport = { fg = c.fg },
  LazyProgressDone = { fg = c.func, bold = true },
  LazyProgressTodo = { fg = c.line_nr, bold = true },
  LazyCommit = { fg = c.fg_muted },
  LazyCommitIssue = { fg = c.constant },
  LazyDimmed = { fg = c.fg_muted },

  -------------------------------------------------------- treesitter tools --
  TreesitterContext = { bg = c.bg_cursorline },
  TreesitterContextLineNumber = { fg = c.line_nr, bg = c.bg_cursorline },
  TSNodeKey = { fg = c.accent, bold = true },
  TSNodeUnmatched = { fg = c.fg_muted },
}
