-- Legacy syntax groups, treesitter captures and LSP semantic tokens.
-- Mapping follows the `syntax` block of the Zed JetBrains Dark theme.
local c = require 'jetbrains.palette'

return {
  ------------------------------------------------------- legacy vim groups --
  Comment = { fg = c.comment },
  Constant = { fg = c.constant, italic = true },
  String = { fg = c.string },
  Character = { fg = c.string },
  Number = { fg = c.number },
  Float = { fg = c.number },
  Boolean = { fg = c.keyword },
  Identifier = { fg = c.fg },
  Function = { fg = c.func },
  Statement = { fg = c.keyword },
  Conditional = { fg = c.control, bold = true },
  Repeat = { fg = c.control, bold = true },
  Label = { fg = c.keyword },
  Operator = { fg = c.fg },
  Keyword = { fg = c.keyword },
  Exception = { fg = c.control, bold = true },
  PreProc = { fg = c.keyword },
  Include = { fg = c.keyword },
  Define = { fg = c.keyword },
  Macro = { fg = c.func_special },
  PreCondit = { fg = c.keyword },
  Type = { fg = c.type },
  StorageClass = { fg = c.keyword },
  Structure = { fg = c.type },
  Typedef = { fg = c.type },
  Special = { fg = c.punct_special },
  SpecialChar = { fg = c.keyword },
  Tag = { fg = c.tag },
  Delimiter = { fg = c.fg },
  SpecialComment = { fg = c.doc, italic = true },
  Debug = { fg = c.warning },
  Underlined = { fg = c.link_text, underline = true },
  Ignore = { fg = c.ignored },
  Error = { fg = c.error },
  Todo = { fg = c.bg, bg = c.warning, bold = true },

  ---------------------------------------------------- treesitter: comments --
  ['@comment'] = { fg = c.comment },
  ['@comment.documentation'] = { fg = c.doc, italic = true },
  ['@comment.error'] = { fg = c.error, bold = true },
  ['@comment.warning'] = { fg = c.warning, bold = true },
  ['@comment.todo'] = { fg = c.bg, bg = c.warning, bold = true },
  ['@comment.note'] = { fg = c.bg, bg = c.info, bold = true },

  --------------------------------------------------- treesitter: keywords --
  -- Zed splits plain keywords (#cf8e6d) from operator.controlFlow (#cc7832 bold).
  ['@keyword'] = { fg = c.keyword },
  ['@keyword.function'] = { fg = c.keyword },
  ['@keyword.operator'] = { fg = c.keyword },
  ['@keyword.import'] = { fg = c.keyword },
  ['@keyword.type'] = { fg = c.keyword },
  ['@keyword.modifier'] = { fg = c.keyword },
  ['@keyword.coroutine'] = { fg = c.keyword },
  ['@keyword.debug'] = { fg = c.warning },
  ['@keyword.directive'] = { fg = c.keyword },
  ['@keyword.directive.define'] = { fg = c.keyword },
  ['@keyword.repeat'] = { fg = c.control, bold = true },
  ['@keyword.return'] = { fg = c.control, bold = true },
  ['@keyword.conditional'] = { fg = c.control, bold = true },
  ['@keyword.conditional.ternary'] = { fg = c.fg },
  ['@keyword.exception'] = { fg = c.control, bold = true },

  ------------------------------------------------ treesitter: identifiers --
  ['@variable'] = { fg = c.variable },
  ['@variable.builtin'] = { fg = c.var_special },
  ['@variable.parameter'] = { fg = c.fg },
  ['@variable.parameter.builtin'] = { fg = c.var_special },
  ['@variable.member'] = { fg = c.property },

  ['@constant'] = { fg = c.constant, italic = true },
  ['@constant.builtin'] = { fg = c.keyword },
  ['@constant.macro'] = { fg = c.func_special },

  ['@module'] = { fg = c.fg },
  ['@module.builtin'] = { fg = c.interface },
  ['@label'] = { fg = c.keyword },

  ---------------------------------------------------- treesitter: strings --
  ['@string'] = { fg = c.string },
  ['@string.documentation'] = { fg = c.doc, italic = true },
  ['@string.regexp'] = { fg = c.string },
  ['@string.escape'] = { fg = c.keyword },
  ['@string.special'] = { fg = c.link_text },
  ['@string.special.symbol'] = { fg = c.constant },
  ['@string.special.path'] = { fg = c.link_text },
  ['@string.special.url'] = { fg = c.link_uri, underline = true },

  ['@character'] = { fg = c.string },
  ['@character.special'] = { fg = c.keyword },
  ['@number'] = { fg = c.number },
  ['@number.float'] = { fg = c.number },
  ['@boolean'] = { fg = c.keyword },

  ------------------------------------------------------ treesitter: types --
  ['@type'] = { fg = c.type },
  ['@type.builtin'] = { fg = c.keyword },
  ['@type.definition'] = { fg = c.type },
  ['@type.qualifier'] = { fg = c.keyword },
  ['@attribute'] = { fg = c.attribute },
  ['@attribute.builtin'] = { fg = c.attribute },
  ['@property'] = { fg = c.property },

  -------------------------------------------------- treesitter: functions --
  ['@function'] = { fg = c.func },
  ['@function.builtin'] = { fg = c.func_special },
  ['@function.call'] = { fg = c.func },
  ['@function.macro'] = { fg = c.func_special },
  ['@function.method'] = { fg = c.func },
  ['@function.method.call'] = { fg = c.func },
  ['@constructor'] = { fg = c.constructor, italic = true },
  ['@operator'] = { fg = c.fg },

  ------------------------------------------------ treesitter: punctuation --
  ['@punctuation.delimiter'] = { fg = c.fg },
  ['@punctuation.bracket'] = { fg = c.fg },
  ['@punctuation.special'] = { fg = c.punct_special },

  -------------------------------------------------- treesitter: markup/md --
  ['@markup.strong'] = { fg = c.fg, bold = true },
  ['@markup.italic'] = { fg = c.fg, italic = true },
  ['@markup.strikethrough'] = { fg = c.fg, strikethrough = true },
  ['@markup.underline'] = { underline = true },
  ['@markup.heading'] = { fg = c.constant, bold = true },
  ['@markup.heading.1'] = { fg = c.constant, bold = true },
  ['@markup.heading.2'] = { fg = c.constant, bold = true },
  ['@markup.heading.3'] = { fg = c.constant },
  ['@markup.heading.4'] = { fg = c.constant },
  ['@markup.heading.5'] = { fg = c.constant },
  ['@markup.heading.6'] = { fg = c.constant },
  ['@markup.quote'] = { fg = c.comment, italic = true },
  ['@markup.math'] = { fg = c.number },
  ['@markup.link'] = { fg = c.link_text },
  ['@markup.link.label'] = { fg = c.link_text },
  ['@markup.link.url'] = { fg = c.link_uri, underline = true },
  ['@markup.raw'] = { fg = c.string },
  ['@markup.raw.block'] = { fg = c.string },
  ['@markup.list'] = { fg = c.fg },
  ['@markup.list.checked'] = { fg = c.success },
  ['@markup.list.unchecked'] = { fg = c.fg_dim },

  ['@diff.plus'] = { fg = c.git_add, bg = c.git_add_bg },
  ['@diff.minus'] = { fg = c.git_delete, bg = c.git_delete_bg },
  ['@diff.delta'] = { fg = c.git_change },

  ['@tag'] = { fg = c.tag },
  ['@tag.builtin'] = { fg = c.tag },
  ['@tag.attribute'] = { fg = c.attribute },
  ['@tag.delimiter'] = { fg = c.fg },

  -------------------------------------------- treesitter: language extras --
  ['@variable.member.key'] = { fg = c.property },
  ['@lifetime'] = { fg = c.lifetime, italic = true },
  ['@type.interface'] = { fg = c.interface },
  ['@constant.enum'] = { fg = c.enum_member, italic = true },
  ['@none'] = {},

  -- css / scss
  ['@tag.css'] = { fg = c.tag },
  ['@property.css'] = { fg = c.property },
  ['@type.css'] = { fg = c.tag },
  ['@string.plain.css'] = { fg = c.string },
  cssClassName = { fg = c.tag },
  cssIdentifier = { fg = c.tag },
  cssTagName = { fg = c.tag },

  -- rust
  ['@module.crate_root.rust'] = { fg = c.interface },

  ---------------------------------------------------- LSP semantic tokens --
  ['@lsp.type.class'] = { fg = c.type },
  ['@lsp.type.comment'] = {},
  ['@lsp.type.decorator'] = { fg = c.attribute },
  ['@lsp.type.enum'] = { fg = c.type, italic = true },
  ['@lsp.type.enumMember'] = { fg = c.enum_member, italic = true },
  ['@lsp.type.event'] = { fg = c.type },
  ['@lsp.type.function'] = { fg = c.func },
  ['@lsp.type.interface'] = { fg = c.interface },
  ['@lsp.type.keyword'] = { fg = c.keyword },
  ['@lsp.type.lifetime'] = { fg = c.lifetime, italic = true },
  ['@lsp.type.macro'] = { fg = c.func_special },
  ['@lsp.type.method'] = { fg = c.func },
  ['@lsp.type.modifier'] = { fg = c.keyword },
  ['@lsp.type.namespace'] = { fg = c.fg },
  ['@lsp.type.number'] = { fg = c.number },
  ['@lsp.type.operator'] = { fg = c.fg },
  ['@lsp.type.parameter'] = { fg = c.fg },
  ['@lsp.type.property'] = { fg = c.property },
  ['@lsp.type.regexp'] = { fg = c.string },
  ['@lsp.type.selfKeyword'] = { fg = c.var_special },
  ['@lsp.type.string'] = { fg = c.string },
  ['@lsp.type.struct'] = { fg = c.type },
  ['@lsp.type.type'] = { fg = c.type },
  ['@lsp.type.typeAlias'] = { fg = c.type },
  ['@lsp.type.typeParameter'] = { fg = c.type_param },
  ['@lsp.type.variable'] = {}, -- let treesitter own plain variables

  ['@lsp.typemod.function.declaration'] = { fg = c.func },
  ['@lsp.typemod.function.defaultLibrary'] = { fg = c.func_special },
  ['@lsp.typemod.method.defaultLibrary'] = { fg = c.func_special },
  ['@lsp.typemod.variable.readonly'] = { fg = c.constant, italic = true },
  ['@lsp.typemod.variable.defaultLibrary'] = { fg = c.var_special },
  ['@lsp.typemod.variable.global'] = { fg = c.constant, italic = true },
  ['@lsp.typemod.property.readonly'] = { fg = c.property },
  ['@lsp.typemod.class.defaultLibrary'] = { fg = c.keyword },
  ['@lsp.typemod.type.defaultLibrary'] = { fg = c.keyword },
  ['@lsp.mod.deprecated'] = { strikethrough = true },
}
